---
name: Release
on:
  push:
    tags:
      - "*"


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.1
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-
      - name: Install dependencies
        run: go mod tidy
      - name: Build binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o bin/jenklog-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -o bin/jenklog-darwin-amd64
          GOOS=windows GOARCH=amd64 go build -o bin/jenklog-windows-amd64.exe
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bin/jenklog-linux-amd64
            bin/jenklog-darwin-amd64
            bin/jenklog-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
